name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # chạy mỗi ngày lúc 0h UTC
  workflow_dispatch: # cho phép chạy tay thủ công

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: kieugiathinh
          outputs: |
            dist/github-snake.svg
            dist/github-snake.gif
          theme_path: ./themes/mytheme.json

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
